### ISSUE TITLE
No adaptation navigation bar

### ISSUE THREAD

**Issue by huangboju** [ruslanskorb/RSKCollectionViewRetractableFirstItemLayout#1]

**Comment by ruslanskorb** [comment]
Hi @huangboju!

Sorry for the late reply.
Could you provide more information on this issue?

Thanks!
Ruslan

**Comment by ruslanskorb** [comment]
@huangboju ping

**Comment by huangboju** [comment]
![screen shot 2018-06-21 at 2 00 12 pm](https://user-images.githubusercontent.com/14818224/41700599-7874c38a-755b-11e8-9b33-6f84f31c233d.png)
If under nav，it is frame not ok

**Comment by ruslanskorb** [comment]
@huangboju What do you mean by "its frame is not ok"?

**Comment by ruslanskorb** [comment]
@huangboju ping

**Comment by ruslanskorb** [comment]
At the moment, for me, everything looks as it should. So, I will close the issue.
If you have additional information, feel free to reopen it.
